#version 450

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

//Buffer of data going in
//layout(set = 0, binding = 0) readonly buffer DataIn 
//{
//   int dataIn[];
//};

//Buffer of data going out
//layout(set = 1, binding = 0) buffer DataOut 
//{
//   int dataOut[];
//};

void main() 
{
  //Get data to edit in this tread
  //int current = dataIn[gl_GlobalInvocationID.x];

  //Update data
  //dataOut[gl_GlobalInvocationID.x] = current++;
}